version: 0.2

env:
  variables:
    TERRAFORM_VERSION: 1.0.9
    ENVIRONMENT: develop

phases:
  install:
    commands:
      - echo install-phase
      - apt-get update && apt-get install -y gnupg software-properties-common curl
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && apt-get install terraform=$TERRAFORM_VERSION
    finally:
      - terraform --version
      - env
  pre_build:
    commands:
      - terraform init -backend-config=config/$ENVIRONMENT.conf
      - terraform validate 
  build:
    commands:
      - echo build-phase
      - terraform plan -var-file=config/$ENVIRONMENT.tfvars -out=tfplan
  post_build:
    commands:
      - echo Entered the build phase...
      - ls -lrt
artifacts:
  files:
    - 'tfplan'
  name: tfplan-$(date +%Y-%m-%d)
